services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - projetojpanelioalves:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf

volumes:
  projetojpanelioalves:
